/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authLayoutImport } from './routes/(auth)/_layout'
import { Route as authLayoutIndexImport } from './routes/(auth)/_layout/index'
import { Route as authLayoutHomeImport } from './routes/(auth)/_layout/home'

// Create Virtual Routes

const authImport = createFileRoute('/(auth)')()

// Create/Update Routes

const authRoute = authImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const authLayoutRoute = authLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => authRoute,
} as any)

const authLayoutIndexRoute = authLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLayoutRoute,
} as any)

const authLayoutHomeRoute = authLayoutHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => authLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authLayoutImport
      parentRoute: typeof authRoute
    }
    '/(auth)/_layout/home': {
      id: '/(auth)/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof authLayoutHomeImport
      parentRoute: typeof authLayoutImport
    }
    '/(auth)/_layout/': {
      id: '/(auth)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authLayoutIndexImport
      parentRoute: typeof authLayoutImport
    }
  }
}

// Create and export the route tree

interface authLayoutRouteChildren {
  authLayoutHomeRoute: typeof authLayoutHomeRoute
  authLayoutIndexRoute: typeof authLayoutIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLayoutHomeRoute: authLayoutHomeRoute,
  authLayoutIndexRoute: authLayoutIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface authRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof authLayoutIndexRoute
  '/home': typeof authLayoutHomeRoute
}

export interface FileRoutesByTo {
  '/home': typeof authLayoutHomeRoute
  '/': typeof authLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_layout': typeof authLayoutRouteWithChildren
  '/(auth)/_layout/home': typeof authLayoutHomeRoute
  '/(auth)/_layout/': typeof authLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/'
  id:
    | '__root__'
    | '/(auth)'
    | '/(auth)/_layout'
    | '/(auth)/_layout/home'
    | '/(auth)/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRoute: typeof authRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  authRoute: authRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/_layout"
      ]
    },
    "/(auth)/_layout": {
      "filePath": "(auth)/_layout.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/_layout/home",
        "/(auth)/_layout/"
      ]
    },
    "/(auth)/_layout/home": {
      "filePath": "(auth)/_layout/home.tsx",
      "parent": "/(auth)/_layout"
    },
    "/(auth)/_layout/": {
      "filePath": "(auth)/_layout/index.tsx",
      "parent": "/(auth)/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
